### ISSUE TITLE
License makes it incompatible with Zimbra

### ISSUE THREAD

**Issue by quanah** [wolfyzvf/Zimbra-Collaboration-Bash-Completion#1]
Note that Zimbra is under the GPLv2, and the GPLv2 and GPLv3 are not compatible.  Thus it is impossible to use this w/o violating the license in general.

I'd also note that rather than using ldapsearch, I'd suggest a generic net::ldap or net::ldapapi perl wrapper, or python-ldap, to include with this. ;)

**Comment by wolfyzvf** [comment]
Yep you right, I'll move the licence to GPLv2 missed that part. Thanks for pointing it out  :)

In my own opinion, moving to perl or python will require to have dependencies that are not build in Zimbra per default. My main goal is to have a lightweight, portable solution. That's why I've turned to ldapsearch as the zmprov command was really slow to respond.

But any contributions are welcomed :)

**Comment by quanah** [comment]
I'm not sure what you mean about the perl dependencies not being there.  Net::LDAP and Net::LDAPapi have been shipped with Zimbra since at least ZCS 4.5, and are heavily used by Zimbra's installation process among other things.

**Comment by quanah** [comment]
Thanks for fixing the license :+1:
